In [ ]:
creating and manipulation arrray _ 


In [4]:
import numpy as np

a = np.array([[11, 12,33],[14, 15, 6]])
b = np.array([[6, 15, 14], [33, 22, 11]])

add = a + b
sub = a - b
mul = a * b
div = a / b

v1 = np.array([11, 12, 33])
v2 = np.array([6, 15, 14])

dot = np.dot(v1, v2)
cross = np.cross(v1, v2)

print("addition:\n", add)
print("subtraction:\n", sub)
print("multiplication:\n", mul)
print("division:\n", div)
print("dot product:\n", dot)
print("cross product:\n", cross)

addition:
 [[17 27 47]
 [47 37 17]]
subtraction:
 [[  5  -3  19]
 [-19  -7  -5]]
multiplication:
 [[ 66 180 462]
 [462 330  66]]
division:
 [[1.83333333 0.8        2.35714286]
 [0.42424242 0.68181818 0.54545455]]
dot product:
 708
cross product:
 [-327   44   93]


In [8]:
import numpy as np
list=(11, 12, 33)
array=np.array(list)
print(array)

list2d=[[21, 32, 13], [45, 56, 16]]
array2d=np.array(list2d)
print(array2d)

list3d=[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]
array3d=np.array(list3d)
print(array3d)

reshaped_array = array2d.reshape(3, 2)
print("Reshaped array:\n", reshaped_array)
sliced_array = array2d[0:3, 0:1]
print("Sliced array:\n", sliced_array)
indexed_element = array2d[1, 2]
print("Indexed element:", indexed_element)


[11 12 33]
[[21 32 13]
 [45 56 16]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Reshaped array:
 [[21 32]
 [13 45]
 [56 16]]
Sliced array:
 [[21]
 [45]]
Indexed element: 16


In [9]:
# for statistics operations
from statistics import correlation

import numpy as np
data = np.array([1, 2, 3, 4, 5])
m = np.mean(data)
med = np.median(data)
dev = np.std(data)
variance = np.var(data)
correleation = np.corrcoef(data, data)
print("Mean:", m)
print("Median:", med)
print("Standard Deviation:", dev)
print("Variance:", variance)
print("Correlation:", correleation)  

Mean: 3.0
Median: 3.0
Standard Deviation: 1.4142135623730951
Variance: 2.0
Correlation: [[1. 1.]
 [1. 1.]]
