In [4]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[6, 5, 4], [3, 2, 1]])

add = a + b
sub = a - b
mul = a * b
div = a / b

v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

dot = np.dot(v1, v2)
cross = np.cross(v1, v2)

print("addition:\n", add)
print("subtraction:\n", sub)
print("multiplication:\n", mul)
print("division:\n", div)
print("dot product:\n", dot)
print("cross product:\n", cross)

addition:
 [[7 7 7]
 [7 7 7]]
subtraction:
 [[-5 -3 -1]
 [ 1  3  5]]
multiplication:
 [[ 6 10 12]
 [12 10  6]]
division:
 [[0.16666667 0.4        0.75      ]
 [1.33333333 2.5        6.        ]]
dot product:
 32
cross product:
 [-3  6 -3]


In [1]:
import numpy as np
list=(1, 2, 3)
array=np.array(list)
print(array)

list2d=[[1, 2, 3], [4, 5, 6]]
array2d=np.array(list2d)
print(array2d)

list3d=[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]
array3d=np.array(list3d)
print(array3d)

reshaped_array = array2d.reshape(3, 2)
print("Reshaped array:\n", reshaped_array)
sliced_array = array2d[0:1, 0:2]
print("Sliced array:\n", sliced_array)
indexed_element = array2d[1, 2]
print("Indexed element:", indexed_element)


[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Reshaped array:
 [[1 2]
 [3 4]
 [5 6]]
Sliced array:
 [[1 2]]
Indexed element: 6


In [2]:
# for statistics operations
from statistics import correlation

import numpy as np
data = np.array([1, 2, 3, 4, 5])
mean = np.mean(data)
median = np.median(data)
std_dev = np.std(data)
variance = np.var(data)
correleation = np.corrcoef(data, data)
print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)
print("Variance:", variance)
print("Correlation:", correlation)  

Mean: 3.0
Median: 3.0
Standard Deviation: 1.4142135623730951
Variance: 2.0
Correlation: <function correlation at 0x71fc8c1349a0>
